spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.140:3306/bank?useUnicode=true&characterEncoding=utf-8
    userName: bank
    password: bank
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  redis:
      host: 192.168.1.140
      port: 6379
      user-prefix: "user-"
      token-prefix: "token-"
      dict-prefix: "dict-"
  resources:
    static-locations: file:${upLoad.FilePath}
jwt:
  header: token
  secret: mySecret
  expiration: 604800
  tokenHead: "bank-"
  route:
    authentication:
      path: auth
      refresh: refresh

upLoad:
  FilePath: E:/bank/upload/img/
  FileFormat: .jpg,.gif,.jpeg,.bmp,.png
  FileSize: 10
  FileSizeAll: 100
logging:
  level: debug